Avoid class verification on WebView startup for M and below
This add the utility class ApiHelperForN. It moves references to
ServiceWorkerControllerAdapter and TokenBindingManagerAdapter, which
were added in N, into the separate class. On pre-N devices, this reduces
log spam caused by a NoClassDefFoundError. It also improves startup
time.

org.chromium.android_webview.test.AwServiceWorkerClientTest#.

Bug: 791099, 838702
Test: adb logcat | grep 'Failed resolution of'
Test: run_webview_instrumentation_test_apk -f
Change-Id: I519075e03bee8c04a3f03a3ff3d316e1473dcc31
Reviewed-on: https://chromium-review.googlesource.com/1098225
Reviewed-by: Bo <boliu@chromium.org>
Reviewed-by: Nate Fischer <ntfschr@chromium.org>
Commit-Queue: James Wallace-Lee <jamwalla@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#566966}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2ad7180f4915ce69643a9db7a358334320318ba5